# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

jobs:
- deployment: scheduled_task
  displayName: Deploy script as scheduled task  
  environment:
    name: Development
    resourceType: VirtualMachine
    tags: development
  strategy:
   runOnce:
     deploy:
      steps:
        - task: Bash@3
          inputs:
            targetType: inline
            script: |
              # Hello world
              hostnamectl
