# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  workingDirectory: '$(System.DefaultWorkingDirectory)/'
  vmImageName: 'ubuntu-latest'
  deployPath: '/opt/connorgp/cron'

stages:
- stage: Test
  displayName: Code Tests
  jobs:
    - job: Test
      displayName: Code Tests
      pool:
        vmImage: $(vmImageName)
      steps:
        - task: UsePythonVersion@0
          inputs:
            versionSpec: 3.8
            addToPath: true
            architecture: x64

        - bash: |
            pip install pytest
            pip install pytest-cov
            pip install faker
          workingDirectory: $(workingDirectory)
          displayName: Install pytest

        - bash: |
            pip install -r requirements.txt
          workingDirectory: $(workingDirectory)
          displayName: Install project requirements for tests

        - bash: |
            pytest tests --doctest-modules --junitxml=junit/test-results.xml --cov=. --cov-report=xml --cov-report=html
          workingDirectory: $(workingDirectory)
          displayName: Test with pytest

        - task: PublishTestResults@2
          condition: succeededOrFailed()
          inputs:
            testResultsFiles: '**/test-*.xml'
            testRunTitle: 'Publish test resutls for Python $(python.version)'

        - task: PublishCodeCoverageResults@1
          inputs:
            codeCoverageTool: Cobertura
            summaryFileLocation: '$(workingDirectory)/**/coverage.xml'
